//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcadiasDavet_Web.NetGsmSms {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms/", ConfigurationName="NetGsmSms.smsnn")]
    public interface smsnn {
        
        // CODEGEN: İleti bölümü ad alanı (SMS), varsayılan değerle (http://sms/) eşleşmediğinden ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse sms_gonder_nn(ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse> sms_gonder_nnAsync(ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV2Request", ReplyAction="http://sms/smsnn/smsGonderNNV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response smsGonderNNV2(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV2Request", ReplyAction="http://sms/smsnn/smsGonderNNV2Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response> smsGonderNNV2Async(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse gondericiadlari(ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse> gondericiadlariAsync(ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.gelensmsResponse gelensms(ArcadiasDavet_Web.NetGsmSms.gelensmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsResponse> gelensmsAsync(ArcadiasDavet_Web.NetGsmSms.gelensmsRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsV2Request", ReplyAction="http://sms/smsnn/gelensmsV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response gelensmsV2(ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsV2Request", ReplyAction="http://sms/smsnn/gelensmsV2Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response> gelensmsV2Async(ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV3Request", ReplyAction="http://sms/smsnn/smsGonderNNV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response smsGonderNNV3(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV3Request", ReplyAction="http://sms/smsnn/smsGonderNNV3Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response> smsGonderNNV3Async(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse sms_gonder_1n(ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse> sms_gonder_1nAsync(ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV2Request", ReplyAction="http://sms/smsnn/smsGonder1NV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response smsGonder1NV2(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV2Request", ReplyAction="http://sms/smsnn/smsGonder1NV2Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response> smsGonder1NV2Async(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV3Request", ReplyAction="http://sms/smsnn/smsGonder1NV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response smsGonder1NV3(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV3Request", ReplyAction="http://sms/smsnn/smsGonder1NV3Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response> smsGonder1NV3Async(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.krediResponse kredi(ArcadiasDavet_Web.NetGsmSms.krediRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.krediResponse> krediAsync(ArcadiasDavet_Web.NetGsmSms.krediRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse paketkampanya(ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse> paketkampanyaAsync(ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.raporResponse rapor(ArcadiasDavet_Web.NetGsmSms.raporRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporResponse> raporAsync(ArcadiasDavet_Web.NetGsmSms.raporRequest request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.rapor_v2Response rapor_v2(ArcadiasDavet_Web.NetGsmSms.rapor_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.rapor_v2Response> rapor_v2Async(ArcadiasDavet_Web.NetGsmSms.rapor_v2Request request);
        
        // CODEGEN: 'return' parametresi, parametre modunu kullanmadan yakalanamayan ek şema bilgilerini gerektiriyor. Özel öznitelik: 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporV3Request", ReplyAction="http://sms/smsnn/raporV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ArcadiasDavet_Web.NetGsmSms.raporV3Response raporV3(ArcadiasDavet_Web.NetGsmSms.raporV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporV3Request", ReplyAction="http://sms/smsnn/raporV3Response")]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporV3Response> raporV3Async(ArcadiasDavet_Web.NetGsmSms.raporV3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nn", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_nnRequest() {
        }
        
        public sms_gonder_nnRequest(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nnResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="SMS")]
        public string @return;
        
        public sms_gonder_nnResponse() {
        }
        
        public sms_gonder_nnResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonderNNV2Request() {
        }
        
        public smsGonderNNV2Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV2Response() {
        }
        
        public smsGonderNNV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlari", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gondericiadlariRequest() {
        }
        
        public gondericiadlariRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlariResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gondericiadlariResponse() {
        }
        
        public gondericiadlariResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensms", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gelensmsRequest() {
        }
        
        public gelensmsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsResponse() {
        }
        
        public gelensmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public gelensmsV2Request() {
        }
        
        public gelensmsV2Request(string username, string password, string startdate, string stopdate, int type) {
            this.username = username;
            this.password = password;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsV2Response() {
        }
        
        public gelensmsV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonderNNV3Request() {
        }
        
        public smsGonderNNV3Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV3Response() {
        }
        
        public smsGonderNNV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1n", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_1nRequest() {
        }
        
        public sms_gonder_1nRequest(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1nResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sms_gonder_1nResponse() {
        }
        
        public sms_gonder_1nResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonder1NV2Request() {
        }
        
        public smsGonder1NV2Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV2Response() {
        }
        
        public smsGonder1NV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonder1NV3Request() {
        }
        
        public smsGonder1NV3Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV3Response() {
        }
        
        public smsGonder1NV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kredi", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public krediRequest() {
        }
        
        public krediRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="krediResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public krediResponse() {
        }
        
        public krediResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanya", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public paketkampanyaRequest() {
        }
        
        public paketkampanyaRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanyaResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public paketkampanyaResponse() {
        }
        
        public paketkampanyaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        public raporRequest() {
        }
        
        public raporRequest(string username, string password, string bulkid, int status, int version) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporResponse() {
        }
        
        public raporResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public rapor_v2Request() {
        }
        
        public rapor_v2Request(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
            this.telno = telno;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public rapor_v2Response() {
        }
        
        public rapor_v2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public raporV3Request() {
        }
        
        public raporV3Request(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.telno = telno;
            this.header = header;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
            this.status = status;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporV3Response() {
        }
        
        public raporV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsnnChannel : ArcadiasDavet_Web.NetGsmSms.smsnn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsnnClient : System.ServiceModel.ClientBase<ArcadiasDavet_Web.NetGsmSms.smsnn>, ArcadiasDavet_Web.NetGsmSms.smsnn {
        
        public smsnnClient() {
        }
        
        public smsnnClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsnnClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse ArcadiasDavet_Web.NetGsmSms.smsnn.sms_gonder_nn(ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nn(request);
        }
        
        public string sms_gonder_nn(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest inValue = new ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).sms_gonder_nn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.sms_gonder_nnAsync(ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nnAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnResponse> sms_gonder_nnAsync(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest inValue = new ArcadiasDavet_Web.NetGsmSms.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).sms_gonder_nnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonderNNV2(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request request) {
            return base.Channel.smsGonderNNV2(request);
        }
        
        public string smsGonderNNV2(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonderNNV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response> ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonderNNV2Async(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request request) {
            return base.Channel.smsGonderNNV2Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Response> smsGonderNNV2Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonderNNV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonderNNV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse ArcadiasDavet_Web.NetGsmSms.smsnn.gondericiadlari(ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest request) {
            return base.Channel.gondericiadlari(request);
        }
        
        public string gondericiadlari(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest inValue = new ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gondericiadlari(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.gondericiadlariAsync(ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest request) {
            return base.Channel.gondericiadlariAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gondericiadlariResponse> gondericiadlariAsync(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest inValue = new ArcadiasDavet_Web.NetGsmSms.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gondericiadlariAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.gelensmsResponse ArcadiasDavet_Web.NetGsmSms.smsnn.gelensms(ArcadiasDavet_Web.NetGsmSms.gelensmsRequest request) {
            return base.Channel.gelensms(request);
        }
        
        public string gelensms(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.gelensmsRequest inValue = new ArcadiasDavet_Web.NetGsmSms.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            ArcadiasDavet_Web.NetGsmSms.gelensmsResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gelensms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.gelensmsAsync(ArcadiasDavet_Web.NetGsmSms.gelensmsRequest request) {
            return base.Channel.gelensmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsResponse> gelensmsAsync(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.gelensmsRequest inValue = new ArcadiasDavet_Web.NetGsmSms.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gelensmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response ArcadiasDavet_Web.NetGsmSms.smsnn.gelensmsV2(ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request request) {
            return base.Channel.gelensmsV2(request);
        }
        
        public string gelensmsV2(string username, string password, string startdate, string stopdate, int type) {
            ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gelensmsV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response> ArcadiasDavet_Web.NetGsmSms.smsnn.gelensmsV2Async(ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request request) {
            return base.Channel.gelensmsV2Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.gelensmsV2Response> gelensmsV2Async(string username, string password, string startdate, string stopdate, int type) {
            ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.gelensmsV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).gelensmsV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonderNNV3(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request request) {
            return base.Channel.smsGonderNNV3(request);
        }
        
        public string smsGonderNNV3(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonderNNV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response> ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonderNNV3Async(ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request request) {
            return base.Channel.smsGonderNNV3Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Response> smsGonderNNV3Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonderNNV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonderNNV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse ArcadiasDavet_Web.NetGsmSms.smsnn.sms_gonder_1n(ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1n(request);
        }
        
        public string sms_gonder_1n(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest inValue = new ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).sms_gonder_1n(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.sms_gonder_1nAsync(ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1nAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nResponse> sms_gonder_1nAsync(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest inValue = new ArcadiasDavet_Web.NetGsmSms.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).sms_gonder_1nAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonder1NV2(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request request) {
            return base.Channel.smsGonder1NV2(request);
        }
        
        public string smsGonder1NV2(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonder1NV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response> ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonder1NV2Async(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request request) {
            return base.Channel.smsGonder1NV2Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Response> smsGonder1NV2Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonder1NV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonder1NV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonder1NV3(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request request) {
            return base.Channel.smsGonder1NV3(request);
        }
        
        public string smsGonder1NV3(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonder1NV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response> ArcadiasDavet_Web.NetGsmSms.smsnn.smsGonder1NV3Async(ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request request) {
            return base.Channel.smsGonder1NV3Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Response> smsGonder1NV3Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.smsGonder1NV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).smsGonder1NV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.krediResponse ArcadiasDavet_Web.NetGsmSms.smsnn.kredi(ArcadiasDavet_Web.NetGsmSms.krediRequest request) {
            return base.Channel.kredi(request);
        }
        
        public string kredi(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.krediRequest inValue = new ArcadiasDavet_Web.NetGsmSms.krediRequest();
            inValue.username = username;
            inValue.password = password;
            ArcadiasDavet_Web.NetGsmSms.krediResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).kredi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.krediResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.krediAsync(ArcadiasDavet_Web.NetGsmSms.krediRequest request) {
            return base.Channel.krediAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.krediResponse> krediAsync(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.krediRequest inValue = new ArcadiasDavet_Web.NetGsmSms.krediRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).krediAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse ArcadiasDavet_Web.NetGsmSms.smsnn.paketkampanya(ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest request) {
            return base.Channel.paketkampanya(request);
        }
        
        public string paketkampanya(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest inValue = new ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).paketkampanya(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.paketkampanyaAsync(ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest request) {
            return base.Channel.paketkampanyaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.paketkampanyaResponse> paketkampanyaAsync(string username, string password) {
            ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest inValue = new ArcadiasDavet_Web.NetGsmSms.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).paketkampanyaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.raporResponse ArcadiasDavet_Web.NetGsmSms.smsnn.rapor(ArcadiasDavet_Web.NetGsmSms.raporRequest request) {
            return base.Channel.rapor(request);
        }
        
        public string rapor(string username, string password, string bulkid, int status, int version) {
            ArcadiasDavet_Web.NetGsmSms.raporRequest inValue = new ArcadiasDavet_Web.NetGsmSms.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            ArcadiasDavet_Web.NetGsmSms.raporResponse retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).rapor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporResponse> ArcadiasDavet_Web.NetGsmSms.smsnn.raporAsync(ArcadiasDavet_Web.NetGsmSms.raporRequest request) {
            return base.Channel.raporAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporResponse> raporAsync(string username, string password, string bulkid, int status, int version) {
            ArcadiasDavet_Web.NetGsmSms.raporRequest inValue = new ArcadiasDavet_Web.NetGsmSms.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).raporAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.rapor_v2Response ArcadiasDavet_Web.NetGsmSms.smsnn.rapor_v2(ArcadiasDavet_Web.NetGsmSms.rapor_v2Request request) {
            return base.Channel.rapor_v2(request);
        }
        
        public string rapor_v2(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            ArcadiasDavet_Web.NetGsmSms.rapor_v2Request inValue = new ArcadiasDavet_Web.NetGsmSms.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            ArcadiasDavet_Web.NetGsmSms.rapor_v2Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).rapor_v2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.rapor_v2Response> ArcadiasDavet_Web.NetGsmSms.smsnn.rapor_v2Async(ArcadiasDavet_Web.NetGsmSms.rapor_v2Request request) {
            return base.Channel.rapor_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.rapor_v2Response> rapor_v2Async(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            ArcadiasDavet_Web.NetGsmSms.rapor_v2Request inValue = new ArcadiasDavet_Web.NetGsmSms.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).rapor_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArcadiasDavet_Web.NetGsmSms.raporV3Response ArcadiasDavet_Web.NetGsmSms.smsnn.raporV3(ArcadiasDavet_Web.NetGsmSms.raporV3Request request) {
            return base.Channel.raporV3(request);
        }
        
        public string raporV3(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            ArcadiasDavet_Web.NetGsmSms.raporV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.raporV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.telno = telno;
            inValue.header = header;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            inValue.status = status;
            inValue.detail = detail;
            ArcadiasDavet_Web.NetGsmSms.raporV3Response retVal = ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).raporV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporV3Response> ArcadiasDavet_Web.NetGsmSms.smsnn.raporV3Async(ArcadiasDavet_Web.NetGsmSms.raporV3Request request) {
            return base.Channel.raporV3Async(request);
        }
        
        public System.Threading.Tasks.Task<ArcadiasDavet_Web.NetGsmSms.raporV3Response> raporV3Async(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            ArcadiasDavet_Web.NetGsmSms.raporV3Request inValue = new ArcadiasDavet_Web.NetGsmSms.raporV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.telno = telno;
            inValue.header = header;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            inValue.status = status;
            inValue.detail = detail;
            return ((ArcadiasDavet_Web.NetGsmSms.smsnn)(this)).raporV3Async(inValue);
        }
    }
}
